name = "renewal-party-rsvp"
main = "worker.js"
compatibility_date = "2026-07-31"
workers_dev = true

# Bind your Cloudflare D1 database here.
d1_databases = [
  { binding = "RSVP_DB", database_name = "renewal-party" }
]
